#!/bin/bash                                                                                                                                                                                      

# Retrieve arguments
domain=$1
path=$2

if [[ ! $path == "" ]]; then
  echo "Only installation on / is supported. You should create a (sub)domain dedicated to monit"
  exit 1
fi

sudo yunohost app checkurl $domain$path -a monit
if [[ ! $? -eq 0 ]]; then 
  exit 1
fi

# Remove trailing "/" for next commands
path=${path%/}

# Configure Nginx and reload
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/monit.conf
sudo service nginx reload
echo $?
