#!/bin/bash

domain=$(sudo yunohost app setting monit domain)
sudo rm /etc/nginx/conf.d/$domain.d/monit.conf
sudo service nginx reload
sudo yunohost app ssowatconf                                                                                                                                                                     
