#!/bin/bash

domain=$(sudo yunohost app setting monit domain)

sudo rm /etc/nginx/conf.d/$domain.d/monit.conf
sudo rm -rf /etc/monit/conf.d/yunohost*

sudo service monit reload
sudo service nginx reload
sudo yunohost app ssowatconf                                                                                                                                                                     
