#!/bin/bash                                                                                                                                                                                      

# Retrieve arguments
domain=$(sudo yunohost app setting monit domain)
path=$(sudo yunohost app setting monit path)

# clean up existing config first
sudo rm -rf /etc/monit/conf.d/yunohost*

sudo cp -ar ../conf/monit/conf.d/* /etc/monit/conf.d
sudo bash -c "echo set alert admin@$(cat /etc/yunohost/current_host) > /etc/monit/conf.d/yunohost-includes/alert"
sudo service monit restart

# Remove trailing "/" for next commands
path=${path%/}

# Configure Nginx and reload
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/monit.conf
sudo service nginx reload
sudo yunohost app ssowatconf                                                                                                                                                                     
